import { User, Role, Status, Color } from './table-demo.model';

export const users = [
    <User> { id: 0, name: 'Jane Doe', role: Role.admin, status: Status.locked, color: Color.red,
        creationDate: new Date(2017, 10, 1), lastLoginDate: new Date(2017, 10, 2) },
    <User> { id: 1, name: 'Joe Bob', role: Role.admin, status: Status.disabled, color: Color.yellow,
        creationDate: new Date(2016, 5, 9), lastLoginDate: new Date(2017, 10, 15) },
    <User> { id: 2, name: 'Mira Manes', role: Role.editor, status: Status.disabled, color: Color.blue,
        creationDate: new Date(2015, 1, 1), lastLoginDate: new Date(2016, 5, 8) },
    <User> { id: 3, name: 'Lebron James', role: Role.editor, status: null, color: Color.blue,
        creationDate: new Date(2014, 8, 17), lastLoginDate: new Date(2016, 9, 12) },
    <User> { id: 4, name: 'George Bush', role: Role.reader, status: Status.locked, color: Color.yellow,
        creationDate: new Date(2015, 12, 23), lastLoginDate: new Date(2016, 8, 29) },
    <User> { id: 5, name: 'Jaracabuschamanjupatoopoo Vader', role: Role.admin, status: Status.locked, color: Color.yellow,
        creationDate: new Date(2013, 12, 8), lastLoginDate: new Date(2017, 9, 15) },
    <User> { id: 6, name: 'Laura Parks', role: Role.editor, status: Status.disabled, color: Color.blue,
        creationDate: new Date(2017, 1, 2), lastLoginDate: new Date(2017, 4, 3) },
    <User> { id: 7, name: 'Jarrod Tops', role: Role.reader, status: null, color: Color.blue,
        creationDate: new Date(2016, 7, 13), lastLoginDate: new Date(2016, 8, 1) },
    <User> { id: 8, name: 'Tony Vello', role: Role.reader, status: null, color: Color.red,
        creationDate: new Date(2017, 3, 12), lastLoginDate: new Date(2017, 4, 1) },
    <User> { id: 9, name: 'Cain McLain', role: Role.editor, status: Status.disabled, color: Color.red,
        creationDate: new Date(2013, 8, 1), lastLoginDate: new Date(2015, 5, 23) },
    <User> { id: 10, name: 'Terrik Man', role: Role.admin, status: Status.disabled, color: Color.blue,
        creationDate: new Date(2014, 8, 5), lastLoginDate: new Date(2015, 3, 1) },
    <User> { id: 11, name: 'Herrold Marks', role: Role.editor, status: null, color: Color.blue,
        creationDate: new Date(2017, 8, 3), lastLoginDate: new Date(2017, 9, 18) },
    <User> { id: 12, name: 'Sarah Calvin', role: Role.editor, status: null, color: Color.blue,
        creationDate: new Date(2012, 10, 1), lastLoginDate: new Date(2018, 12, 13) },
    <User> { id: 13, name: 'Nick Carter', role: Role.admin, status: Status.locked, color: Color.yellow,
        creationDate: new Date(2011, 11, 2), lastLoginDate: new Date(2013, 4, 11) },
    <User> { id: 14, name: 'Diane Cober', role: Role.admin, status: null, color: Color.blue,
        creationDate: new Date(2003, 9, 21), lastLoginDate: new Date(2013, 5, 17) },
    <User> { id: 15, name: 'Phil Itup', role: Role.admin, status: Status.disabled, color: Color.yellow,
        creationDate: new Date(2013, 12, 8), lastLoginDate: new Date(2016, 5, 14) },
    <User> { id: 16, name: 'Giter Dun', role: Role.editor, status: null, color: Color.red,
        creationDate: new Date(2017, 10, 1), lastLoginDate: new Date(2017, 10, 1) },
    <User> { id: 17, name: 'Ashley Knot', role: Role.reader, status: null, color: Color.yellow,
        creationDate: new Date(2016, 5, 9), lastLoginDate: new Date(2017, 3, 16) },
    <User> { id: 18, name: 'Bane Lowery', role: Role.editor, status: null, color: Color.blue,
        creationDate: new Date(2015, 1, 1), lastLoginDate: new Date(2017, 2, 2) },
    <User> { id: 19, name: 'Trevor Bever', role: Role.admin, status: Status.disabled, color: Color.yellow,
        creationDate: new Date(2014, 8, 17), lastLoginDate: new Date(2017, 1, 1) },
    <User> { id: 20, name: 'Yolanda Waters', role: Role.reader, status: null, color: Color.yellow,
        creationDate: new Date(2015, 12, 23), lastLoginDate: new Date(2017, 1, 1) },
    <User> { id: 21, name: 'Barney Dino', role: Role.editor, status: null, color: Color.yellow,
        creationDate: new Date(2017, 1, 2), lastLoginDate: new Date(2017, 1, 3) },
    <User> { id: 22, name: 'Clint Nevins', role: Role.admin, status: Status.disabled, color: Color.blue,
        creationDate: new Date(2013, 8, 1), lastLoginDate: new Date(2017, 3, 3) },
    <User> { id: 23, name: 'Walter Mit', role: Role.editor, status: null, color: Color.blue,
        creationDate: new Date(2013, 8, 1), lastLoginDate: new Date(2014, 9, 7) },
    <User> { id: 24, name: 'Chester McMillian', role: Role.reader, status: Status.locked, color: Color.red,
        creationDate: new Date(2017, 3, 12), lastLoginDate: new Date(2017, 3, 13) },
    <User> { id: 25, name: 'Jill Hill', role: Role.editor, status: null, color: Color.red,
        creationDate: new Date(2017, 3, 12), lastLoginDate: new Date(2017, 7, 11) }
];